export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const SET_LOANDING = "SET_LOANDING";
export const GET_DOGS_DETAILS = "GET_DOGS_DETAILS";
export const GET_DOGS_TEMPERAMENTS = "GET_DOGS_TEMPERAMENTS";
export const FILTER_TEMPERAMENT = "FILTER_TEMPERAMENT";
export const FILTER_DOGS_API = "FILTER_DOGS_API";
export const FILTER_DOGS_BD = "FILTER_DOGS_BD";
export const FILTER_DOGS_WEIGHT_MAX = "FILTER_DOGS_WEIGHT_MAX";
export const FILTER_DOGS_WEIGHT_MIN = "FILTER_DOGS_WEIGHT_MIN";
export const SEARCH_NAME_DOG = "SEARCH_NAME_DOG";

// export const
